name: Gitflow Action for Python Package Development
run-name: ${{ github.event_name }} to ${{ github.ref_name }} by ${{ github.actor }}

on:
  push:
    branches: ['*', '!dev', '!main', '!github_page', '!Conda_Package']    
  pull_request:
    types: ['opened', 'closed']
    branches: ['main', 'release*', 'dev', 'master']
jobs:
  Activating_Parser:
    uses: fnlcr-dmap/gitflow-py/.github/workflows/parser.yml@main
    with:
      artifact_rid_production: "ri.artifacts.main.repository.20ce29a2-3803-4eae-b325-8fe367d47d1e"
      artifact_rid_development: "ri.artifacts.main.repository.99a97542-6794-4913-9281-02819ce47884"
      image_to_use: "ghcr.io/fnlcr-dmap/scsaworkflow:spac_py39"
    secrets:
      NIDAP_TOKEN_PRODUCTION: ${{ secrets.NIDAP_TOKEN_PRODUCTION }}
      NIDAP_TOKEN_DEVELOPMENT: ${{ secrets.NIDAP_TOKEN_DEVELOPMENT }}
