name: Gitflow Action for Python Package Development
run-name: ${{ github.event_name }} to ${{ github.ref_name }} by ${{ github.actor }}

on:
  push:
    branches: ['*', '!dev', '!main', '!github_page', '!Conda_Package']    
  pull_request:
    types: ['opened', 'closed']
    branches: ['main', 'release*', 'dev', 'master']
jobs:
  Activating_Parser:
    uses: fnlcr-dmap/gitflow-py/.github/workflows/parser.yml@main
    with:
      artifact_rid_production: "ri.artifacts.main.repository.ba55e77c-243c-450d-84c3-74713ce194f3"
      artifact_rid_development: "ri.artifacts.main.repository.c2c0fa69-dbc0-483f-90f8-cfb429d405f0"
    secrets:
      NIDAP_TOKEN_PRODUCTION: ${{ secrets.NIDAP_TOKEN_PRODUCTION }}
      NIDAP_TOKEN_DEVELOPMENT: ${{ secrets.NIDAP_TOKEN_DEVELOPMENT }}
