name: Gitflow Action for Python Package Development
run-name: ${{ github.event_name }} to ${{ github.ref_name }} by ${{ github.actor }}

on:
  push:
    branches: ['*', '!dev', '!main', '!github_page', '!Conda_Package']    
  pull_request:
    types: ['opened', 'closed']
    branches: ['main', 'release*', 'dev', 'master']
jobs:
  Activating_Parser:
    uses: fnlcr-dmap/gitflow-py/.github/workflows/parser.yml@main
    with:
      image_to_use: "ghcr.io/ruiheesi/pyscworkflow:dev"
    secrets:
      PAT: ${{ secrets.PAT }}
      NIDAP_TOKEN: ${{ secrets.PAT }}